#! /usr/bin/bash

# Build and run Keycloak container
docker compose up -d

# Install client packages
source ./.venv/bin/activate
pip install -r requirements.txt

# Create realm in Keycloak
python client.py