#! /usr/bin/bash

# Build and run Keycloak container
docker compose up -d

# Install client packages
source ./.venv/bin/activate
pip install -r requirements.txt

# Delay 5 seconds before connect to Keycloak
sleep 5
python client.py